apiVersion: v1
kind: Service
metadata:
  name: testfachdienst
  labels:
    app: testfachdienst
spec:
  type: ClusterIP
  selector:
    app: testfachdienst
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: actuator
      port: 8081
      targetPort: 8081
